[build]
  base = "packages/react-app"
  command = "npm run build"
  publish = ".next"

[dev]
  command = "npm run dev"
  port = 3001
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  SKIP_PREFLIGHT_CHECK = "true"
  CI = "false"
  # Force npm usage instead of yarn
  NPM_USE_PRODUCTION = "false"
  YARN_ENABLED = "false"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Add specific headers for Next.js static files
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Client-side routing support
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
