[build]
  base = "packages/react-app"
  command = "npm run build"
  publish = "out"

[dev]
  command = "npm run dev"
  port = 3001
  publish = "out"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  SKIP_PREFLIGHT_CHECK = "true"
  CI = "false"
  # Force npm usage instead of yarn
  NPM_USE_PRODUCTION = "false"
  YARN_ENABLED = "false"
  # Next.js specific environment variables
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Add specific headers for Next.js static files
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Next.js static export redirects
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

# Client-side routing support for Next.js static export
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
